% Auto-generated by cameraCalibrator app on 27-Jul-2019
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_51.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_33.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_37.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_39.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_42.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_45.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_15_48.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_17_06.jpg',...
    'C:\Users\Bryce\Documents\UNSW\Gits\MTRN4230\Images\table_img_07_11_13_17_22.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
