% read the original image
I = imread('test1.jpg');
% call createMask function to get the mask and the filtered image
[BW,maskedRGBImage] = greenMaskBox(I);
% plot the original image, mask and filtered image all in one figure
%subplot(1,3,1);imshow(I);title('Original Image');
figure(1);imshow(BW);title('Mask');
figure(2);imshow(maskedRGBImage);title('Filtered Image');

function [BW,maskedRGBImage] = greenMaskBox(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 06-Nov-2017
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.953;
channel1Max = 0.017;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.375;
channel2Max = 0.804;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.420;
channel3Max = 0.776;

% Create mask based on chosen histogram thresholds
sliderBW = ( (I(:,:,1) >= channel1Min) | (I(:,:,1) <= channel1Max) ) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;
end